Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.c')

path =  [cwd]
path =  [cwd+'/inc']

group = DefineGroup('Hardware', src, depend = [''], CPPPATH =path)

Return('group')
